"""initial schema (audit N-1)

Bu migratsiya TZ 13-bo'lim ("SQLAlchemy + Alembic") talabini bajarish
uchun yozildi — audit sessiyasigacha `alembic/` katalogi bo'sh edi va
sxema o'zgarishlari qo'lda (git-committed bo'lmagan `ALTER TABLE`) qilinardi
(audit hisobotidagi V-2 voqeasi shu muammoning to'g'ridan-to'g'ri sababi).

Bu revizyoni ATAYLAB audit sessiyasidan OLDINGI sxemani ifodalaydi
(`admins.role`, `bots.force_release_requested`, `relay_log` jadvali —
shu sessiyada qo'shilgan — 0002 revizyosida). Shunday qilib:
- Yangi (bo'sh) baza: `alembic upgrade head` — 0001 keyin 0002, hammasi
  to'g'ri tartibda yaratiladi.
- Mavjud, Alembic'gacha qo'lda boshqarilgan baza (masalan hozirgi
  `data_relay.db`, unda bu sxema ALLAQACHON bor): avval
  `alembic stamp 0001` (hech narsa BAJARMAYDI, faqat "bu baza shu
  bosqichda" deb belgilaydi), keyin `alembic upgrade head` — faqat 0002
  (haqiqatan YETISHMAYOTGAN narsalar) qo'llaniladi. Batafsil: README.md.

Revision ID: 0001
Revises:
Create Date: 2026-07-30 18:07:18.888317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_tg_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_patterns',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('templates',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_busy', sa.Boolean(), nullable=False),
    sa.Column('current_case_id', sa.Integer(), nullable=True),
    sa.Column('total_processed', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('phone_format', sa.String(length=32), nullable=False),
    sa.Column('owner_admin_id', sa.Integer(), nullable=True),
    sa.Column('needs_start_greeting', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['current_case_id'], ['cases.id'], use_alter=True),
    sa.ForeignKeyConstraint(['owner_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('tg_username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('current_coupon', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('NUMBER_RECEIVED', 'SENT_TO_BOT', 'AWAITING_COUPON', 'COUPON_SENT_TO_BOT', 'CONFIRMED', 'REJECTED', 'EXPIRED', 'SUSPICIOUS_HOLD', 'NEEDS_ADMIN', 'TIMEOUT', 'CUSTOMER_TIMEOUT', 'EXPIRED_SESSION', 'DUPLICATE_ACTIVE', 'ALREADY_CONFIRMED', name='casestatus', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('expired_attempts', sa.Integer(), nullable=False),
    sa.Column('admin_redispatch_requested', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('coupon', sa.String(length=16), nullable=False),
    sa.Column('result', sa.Enum('NUMBER_RECEIVED', 'SENT_TO_BOT', 'AWAITING_COUPON', 'COUPON_SENT_TO_BOT', 'CONFIRMED', 'REJECTED', 'EXPIRED', 'SUSPICIOUS_HOLD', 'NEEDS_ADMIN', 'TIMEOUT', 'CUSTOMER_TIMEOUT', 'EXPIRED_SESSION', 'DUPLICATE_ACTIVE', 'ALREADY_CONFIRMED', name='casestatus', native_enum=False, length=32), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon_attempts')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('bots')
    op.drop_table('templates')
    op.drop_table('settings')
    op.drop_table('bot_patterns')
    op.drop_table('audit_log')
    op.drop_table('admins')
    # ### end Alembic commands ###
