"""cases.origin_message_id — mijozning nomer yozgan xabari id'si

Admin o'sha xabarga reply qilib rasm tashlasa, partiya aynan shu
nomerga bog'lanadi (mijozda 2-3 nomer bo'lgan holat).

DIQQAT: autogenerate qo'shgan `uq_cases_short_code` juftligi qo'lda
olib tashlandi — bu o'zgarishga aloqasi yo'q soxta farq.

Asl sarlavha: case_origin_message_id

Revision ID: bb83463e09b6
Revises: c8d4c7176703
Create Date: 2026-08-25 11:29:53.833877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb83463e09b6'
down_revision: Union[str, Sequence[str], None] = 'c8d4c7176703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('origin_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'origin_message_id')
    # ### end Alembic commands ###
